//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllInOne20
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterTable
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string AltPhone { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Intake { get; set; }
        public string PGDegree { get; set; }
        public string PGUNIV { get; set; }
        public Nullable<int> PGPercentage { get; set; }
        public Nullable<int> PGYear { get; set; }
        public string GDegree { get; set; }
        public string GUNIV { get; set; }
        public Nullable<int> GPercentage { get; set; }
        public Nullable<int> GYear { get; set; }
        public string InterDegree { get; set; }
        public string InterUNIV { get; set; }
        public Nullable<int> InterPercentage { get; set; }
        public Nullable<int> InterYear { get; set; }
        public string SSCDegree { get; set; }
        public string SSCUNIV { get; set; }
        public Nullable<int> SSCPercentage { get; set; }
        public Nullable<int> SSCYear { get; set; }
        public Nullable<int> IELTSPTEScore { get; set; }
        public Nullable<int> GREGMAT { get; set; }
        public string CountryChoice { get; set; }
        public string HeardAbout { get; set; }
        public string IELTSPTEImage { get; set; }
        public string PGorGraduateImage { get; set; }
        public string SSCINTERImage { get; set; }
        public string singofStudent { get; set; }
    }
}
